name: flutter_instagclone
description: A new Flutter application.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  image_picker: ^0.7.4
  flutter_icons: ^1.1.0
  cached_network_image: ^2.5.0
  fluttertoast: ^7.1.1
  firebase_database: ^6.1.2
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  firebase_auth: ^1.1.2
  shared_preferences: ^2.0.5
  cloud_firestore: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
  #       - asset: fonts/Schyler-Italic.ttf
